Fix duplicate event, update d2-api version, use new tracker api
EyeSeeTea/Bulk-Load pull request #320
Opened 2024-02-27 16:14 UTC by davidbgomes

### :pushpin: References 

* **Issue:** Closes [Downloading AMC Product Register data results in events duplicated](https://app.clickup.com/t/8693r9fav)

### :memo: Implementation

- This issue was only happening on the deprecated `api/events` endpoint. I've changed the GET events to the new `api/tracker/events`. For that, I had to update to the new version of d2-api (1.13.2-beta.6), and refactor some code based on the new endpoint.

### :fire: Notes for the reviewer

- To test, download a template for the program AMC - Product Register, on the orgUnit Burkina Faso, and populate the template from 01/02/24 to 27/02/24 for example. Before this fix, the events on the second tab came duplicated 5 times each, which was what the API wrongly fetched.

### :video_camera: Screenshots/Screen capture

### :bookmark_tabs: Others

2024-03-05 02:25 UTC, eperedo requested changes
Thanks @davidbgomes. Duplicated events was indeed solved, but I'm getting the following error after trying to import data: `"Event.trackedEntityInstance does not point to a valid tracked entity instance: null"`. I was testing with this file: [AMC - Product Register (5).xlsx](https://github.com/EyeSeeTea/Bulk-Load/files/14489490/AMC.-.Product.Register.5.xlsx)

Also can you please remove the unnecessary Pager type to avoid lint errors:

```ts
src/data/InstanceDhisRepository.ts
  Line 28:5:  'Pager' is defined but never used                                        unused-imports/no-unused-imports
  Line 28:5:  'Pager' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
```

2024-03-07 23:24 UTC, davidbgomes commented
Hello @eperedo 

Thanks for the review! I wasn't able to reproduce that error with that file, it always went through. Could you please try again or double check if that is the file it gave an error?

I've fixed the lint error 👍

2024-06-10 22:34 UTC, eperedo requested changes

2024-06-10 22:34 UTC, eperedo commented on src/data/Dhis2TrackedEntityInstances.ts
> -                trackedEntityInstance: teiId,
I think the error is here. We're using the new api for getting the events, but the import is still using the old endpoint (see `postEvents` method at `src/data/Dhis2Events.ts`).

![image](https://github.com/EyeSeeTea/Bulk-Load/assets/461124/24a9e7db-17dd-4328-8d6b-d51cc995e5e2)

![image](https://github.com/EyeSeeTea/Bulk-Load/assets/461124/f78163a7-38cc-437e-a731-4e485f77e463)

```json
"importSummaries": [
    {
        "responseType": "ImportSummary",
        "status": "ERROR",
        "description": "Event.trackedEntityInstance does not point to a valid tracked entity instance: null",
        "importCount": {
            "imported": 0,
            "updated": 0,
            "ignored": 1,
            "deleted": 0
        },
        "conflicts": [],
        "reference": "zGEzCeey4uE"
    }
],
```

For the old endpoint we need to send `trackedEntityInstance` instead `trackedEntity`.

2024-07-10 21:03 UTC, eperedo commented
@MiquelAdell This is weird, but I cannot reproduce the "duplicate events" bug anymore. Since this was a bug in the `api/events` endpoint looks like it was fixed in v2.38.6. I think we should not merge these changes until we can reproduce the bug again.

2024-09-12 06:37 UTC, closed without merging